import { paramCase } from 'src/utils/change-case';

import { _id, _postTitles } from 'src/_mock/assets';

// ----------------------------------------------------------------------

const MOCK_ID = _id[1];

const MOCK_TITLE = _postTitles[2];

const ROOTS = {
  AUTH: '/auth',
  AUTH_DEMO: '/auth-demo',
  DASHBOARD: '/dashboard',
};

// ----------------------------------------------------------------------

export const paths = {
  comingSoon: '/coming-soon',
  maintenance: '/maintenance',
  pricing: '/pricing',
  payment: '/payment',
  about: '/about-us',
  contact: '/contact-us',
  faqs: '/faqs',
  page403: '/error/403',
  page404: '/error/404',
  page500: '/error/500',
  components: '/components',
  docs: 'https://docs.minimals.cc',
  changelog: 'https://docs.minimals.cc/changelog',
  zoneStore: 'https://mui.com/store/items/zone-landing-page/',
  minimalStore: 'https://mui.com/store/items/minimal-dashboard/',
  freeUI: 'https://mui.com/store/items/minimal-dashboard-free/',
  figma: 'https://www.figma.com/design/cAPz4pYPtQEXivqe11EcDE/%5BPreview%5D-Minimal-Web.v6.0.0',
  product: {
    root: `/product`,
    checkout: `/product/checkout`,
    details: (id) => `/product/${id}`,
    demo: { details: `/product/${MOCK_ID}` },
  },
  post: {
    root: `/post`,
    details: (title) => `/post/${paramCase(title)}`,
    demo: { details: `/post/${paramCase(MOCK_TITLE)}` },
  },
  // AUTH
  auth: {
    amplify: {
      signIn: `${ROOTS.AUTH}/amplify/sign-in`,
      verify: `${ROOTS.AUTH}/amplify/verify`,
      signUp: `${ROOTS.AUTH}/amplify/sign-up`,
      updatePassword: `${ROOTS.AUTH}/amplify/update-password`,
      resetPassword: `${ROOTS.AUTH}/amplify/reset-password`,
    },
    jwt: {
      signIn: `${ROOTS.AUTH}/jwt/sign-in`,
      signUp: `${ROOTS.AUTH}/jwt/sign-up`,
    },
    firebase: {
      signIn: `${ROOTS.AUTH}/firebase/sign-in`,
      verify: `${ROOTS.AUTH}/firebase/verify`,
      signUp: `${ROOTS.AUTH}/firebase/sign-up`,
      resetPassword: `${ROOTS.AUTH}/firebase/reset-password`,
    },
    auth0: {
      signIn: `${ROOTS.AUTH}/auth0/sign-in`,
    },
    supabase: {
      signIn: `${ROOTS.AUTH}/supabase/sign-in`,
      verify: `${ROOTS.AUTH}/supabase/verify`,
      signUp: `${ROOTS.AUTH}/supabase/sign-up`,
      updatePassword: `${ROOTS.AUTH}/supabase/update-password`,
      resetPassword: `${ROOTS.AUTH}/supabase/reset-password`,
    },
  },
  authDemo: {
    split: {
      signIn: `${ROOTS.AUTH_DEMO}/split/sign-in`,
      signUp: `${ROOTS.AUTH_DEMO}/split/sign-up`,
      resetPassword: `${ROOTS.AUTH_DEMO}/split/reset-password`,
      updatePassword: `${ROOTS.AUTH_DEMO}/split/update-password`,
      verify: `${ROOTS.AUTH_DEMO}/split/verify`,
    },
    centered: {
      signIn: `${ROOTS.AUTH_DEMO}/centered/sign-in`,
      signUp: `${ROOTS.AUTH_DEMO}/centered/sign-up`,
      resetPassword: `${ROOTS.AUTH_DEMO}/centered/reset-password`,
      updatePassword: `${ROOTS.AUTH_DEMO}/centered/update-password`,
      verify: `${ROOTS.AUTH_DEMO}/centered/verify`,
    },
  },
  // DASHBOARD
  dashboard: {
    root: ROOTS.DASHBOARD,
    mail: `${ROOTS.DASHBOARD}/mail`,
    chat: `${ROOTS.DASHBOARD}/chat`,
    blank: `${ROOTS.DASHBOARD}/blank`,
    kanban: `${ROOTS.DASHBOARD}/kanban`,
    calendar: `${ROOTS.DASHBOARD}/calendar`,
    fileManager: `${ROOTS.DASHBOARD}/file-manager`,
    permission: `${ROOTS.DASHBOARD}/permission`,
    general: {
      app: `${ROOTS.DASHBOARD}/app`,
      ecommerce: `${ROOTS.DASHBOARD}/ecommerce`,
      analytics: `${ROOTS.DASHBOARD}/analytics`,
      banking: `${ROOTS.DASHBOARD}/banking`,
      booking: `${ROOTS.DASHBOARD}/booking`,
      file: `${ROOTS.DASHBOARD}/file`,
      course: `${ROOTS.DASHBOARD}/course`,
    },
    admin: {
      root: `${ROOTS.DASHBOARD}/admin`,
      schoolyear: `${ROOTS.DASHBOARD}/admin/school_year`,
      createSem: `${ROOTS.DASHBOARD}/admin/create_sem`,
      facultyType: `${ROOTS.DASHBOARD}/admin/faculty_type`,
      user: `${ROOTS.DASHBOARD}/admin/user`,
      campus: `${ROOTS.DASHBOARD}/admin/campus`,
      building: `${ROOTS.DASHBOARD}/admin/building`,
      room: `${ROOTS.DASHBOARD}/admin/room`,
      track: `${ROOTS.DASHBOARD}/admin/track`,
      strand: `${ROOTS.DASHBOARD}/admin/strand`,
      department: `${ROOTS.DASHBOARD}/admin/department`,
      courseGroup: `${ROOTS.DASHBOARD}/admin/course_group`,
      courseCL: `${ROOTS.DASHBOARD}/admin/course_college`,
      programGS: `${ROOTS.DASHBOARD}/admin/program_gs`,
      documentElem: `${ROOTS.DASHBOARD}/admin/documents_elem`,
      documentCollege: `${ROOTS.DASHBOARD}/admin/documents_college`,
      documentGS: `${ROOTS.DASHBOARD}/admin/documents_gs`,
      ept: `${ROOTS.DASHBOARD}/admin/ept_subject`,
      cp: `${ROOTS.DASHBOARD}/admin/company_profile`,
      accessControl: `${ROOTS.DASHBOARD}/admin/access_control`,
    },
    accounting: {
      root: `${ROOTS.DASHBOARD}/accounting`,
      setup: {
        root: `${ROOTS.DASHBOARD}/accounting/setup`,
        discount: `${ROOTS.DASHBOARD}/accounting/setup/discount`,
        payment: `${ROOTS.DASHBOARD}/accounting/setup/payment`,
        counter: `${ROOTS.DASHBOARD}/accounting/setup/counter`,
        coa: `${ROOTS.DASHBOARD}/accounting/setup/coa`,
        feeElem: `${ROOTS.DASHBOARD}/accounting/setup/fee_elem`,
        feeCollege: `${ROOTS.DASHBOARD}/accounting/setup/fee_college`,
      },
      downOverride: `${ROOTS.DASHBOARD}/accounting/down_override`,
      plotDiscount: `${ROOTS.DASHBOARD}/accounting/plot_discount`,
      studentDiscount: `${ROOTS.DASHBOARD}/accounting/student_discount`,
      dcMemo: `${ROOTS.DASHBOARD}/accounting/dc_memo`,
      tagPromisory: `${ROOTS.DASHBOARD}/accounting/tag_promisory`,
      faElem: `${ROOTS.DASHBOARD}/accounting/fa_elem`,
      faShs: `${ROOTS.DASHBOARD}/accounting/fa_shs`,
      faCollege: {
        root: `${ROOTS.DASHBOARD}/accounting/fa_college`,
        tf: `${ROOTS.DASHBOARD}/accounting/fa_college/tf`,
        mf: `${ROOTS.DASHBOARD}/accounting/fa_college/mf`,
        rf: `${ROOTS.DASHBOARD}/accounting/fa_college/rf`,
        sf: `${ROOTS.DASHBOARD}/accounting/fa_college/sf`,
        cf: `${ROOTS.DASHBOARD}/accounting/fa_college/cf`,
      },
      faGS: {
        root: `${ROOTS.DASHBOARD}/accounting/fa_gs`,
        tf: `${ROOTS.DASHBOARD}/accounting/fa_gs/tf`,
        mf: `${ROOTS.DASHBOARD}/accounting/fa_gs/mf`,
        sf: `${ROOTS.DASHBOARD}/accounting/fa_gs/sf`,
      },
      faAdjustElem: {
        root: `${ROOTS.DASHBOARD}/accounting/fa_adjust_elem`,
        addFee: `${ROOTS.DASHBOARD}/accounting/fa_adjust_elem/add_fee`,
        deleteFee: `${ROOTS.DASHBOARD}/accounting/fa_adjust_elem/delete_fee`,
      },
      faAdjustShs: {
        root: `${ROOTS.DASHBOARD}/accounting/fa_adjust_shs`,
        addFee: `${ROOTS.DASHBOARD}/accounting/fa_adjust_shs/add_fee`,
        deleteFee: `${ROOTS.DASHBOARD}/accounting/fa_adjust_shs/delete_fee`,
      },
      faAdjustCollege: {
        root: `${ROOTS.DASHBOARD}/accounting/fa_adjust_college`,
        addFee: `${ROOTS.DASHBOARD}/accounting/fa_adjust_college/add_fee`,
        deleteFee: `${ROOTS.DASHBOARD}/accounting/fa_adjust_college/delete_fee`,
      },
      faAdjustGs: {
        root: `${ROOTS.DASHBOARD}/accounting/fa_adjust_gs`,
        addFee: `${ROOTS.DASHBOARD}/accounting/fa_adjust_gs/add_fee`,
        deleteFee: `${ROOTS.DASHBOARD}/accounting/fa_adjust_gs/delete_fee`,
      },
      psElem: `${ROOTS.DASHBOARD}/accounting/ps_elem`,
      psShs: `${ROOTS.DASHBOARD}/accounting/ps_shs`,
      psCollege: `${ROOTS.DASHBOARD}/accounting/ps_college`,
      batchAssessment: `${ROOTS.DASHBOARD}/accounting/batch_assessment`,
    },
    registrar: {
      root: `${ROOTS.DASHBOARD}/registrar`,
      accreditation: `${ROOTS.DASHBOARD}/registrar/accreditation`,
      assessment: {
        root: `${ROOTS.DASHBOARD}/registrar/assessment`,
        elem: `${ROOTS.DASHBOARD}/registrar/assessment/elem`,
        shs: `${ROOTS.DASHBOARD}/registrar/assessment/shs`,
        college: `${ROOTS.DASHBOARD}/registrar/assessment/college`,
        gs: `${ROOTS.DASHBOARD}/registrar/assessment/gs`,
      },
      credentials: `${ROOTS.DASHBOARD}/registrar/credentials`,
      computeIncomplete: `${ROOTS.DASHBOARD}/registrar/compute-incomplete`,
      comprehensiveExamGrade: `${ROOTS.DASHBOARD}/registrar/comprehensive-exam-grade`,
      enrollment: {
        root: `${ROOTS.DASHBOARD}/registrar/enrollment`,
        elem: `${ROOTS.DASHBOARD}/registrar/enrollment/elem`,
        shs: `${ROOTS.DASHBOARD}/registrar/enrollment/shs`,
        college: `${ROOTS.DASHBOARD}/registrar/enrollment/college`,
        gs: `${ROOTS.DASHBOARD}/registrar/enrollment/gs`,
      },
      enrollmentAdjustment: {
        root: `${ROOTS.DASHBOARD}/registrar/enrollment-adjustment`,
        shs: `${ROOTS.DASHBOARD}/registrar/enrollment-adjustment/shs`,
        college: `${ROOTS.DASHBOARD}/registrar/enrollment-adjustment/college`,
        gs: `${ROOTS.DASHBOARD}/registrar/enrollment-adjustment/gs`,
      },
      enrollmentMonitoringCollege: `${ROOTS.DASHBOARD}/registrar/enrollment-monitoring-college`,
      equivalency: {
        root: `${ROOTS.DASHBOARD}/registrar/equivalency`,
        auto: `${ROOTS.DASHBOARD}/registrar/equivalency/auto`,
        manual: `${ROOTS.DASHBOARD}/registrar/equivalency/manual`,
        gsManual: `${ROOTS.DASHBOARD}/registrar/equivalency/gs-manual`,
      },
      generalSavingGradingSheet: {
        root: `${ROOTS.DASHBOARD}/registrar/general-saving-grading-sheet`,
        elem: `${ROOTS.DASHBOARD}/registrar/general-saving-grading-sheet/elem`,
        college: `${ROOTS.DASHBOARD}/registrar/general-saving-grading-sheet/college`,
      },
      graduationDetails: `${ROOTS.DASHBOARD}/registrar/graduation-details`,
      individualYearLevelingCollege: `${ROOTS.DASHBOARD}/registrar/individual-year-leveling-college`,
      nstpAssignment: `${ROOTS.DASHBOARD}/registrar/nstp-assignment`,
      oldStudent: `${ROOTS.DASHBOARD}/registrar/old-student`,
      restoreGrade: `${ROOTS.DASHBOARD}/registrar/restore-grade`,
      schedule: {
        root: `${ROOTS.DASHBOARD}/registrar/schedule`,
        onlineRegistrationElem: `${ROOTS.DASHBOARD}/registrar/schedule/online-registration-elem`,
        onlineRegistrationShs: `${ROOTS.DASHBOARD}/registrar/schedule/online-registration-shs`,
        onlineRegistrationCollege: `${ROOTS.DASHBOARD}/registrar/schedule/online-registration-college`,
        encodingGradesElem: `${ROOTS.DASHBOARD}/registrar/schedule/encoding-grades-elem`,
        encodingGradesShs: `${ROOTS.DASHBOARD}/registrar/schedule/encoding-grades-shs`,
        encodingGradesCollege: `${ROOTS.DASHBOARD}/registrar/schedule/encoding-grades-college`,
        encodingSectionOffering: `${ROOTS.DASHBOARD}/registrar/schedule/encoding-section-offering`,
        sectionOfferingSchedule: `${ROOTS.DASHBOARD}/registrar/schedule/section-offering-schedule`,
        graduationSchedule: `${ROOTS.DASHBOARD}/registrar/schedule/graduation-schedule`,
      },
      sectionAssignment: {
        root: `${ROOTS.DASHBOARD}/registrar/section-assignment`,
        elem: `${ROOTS.DASHBOARD}/registrar/section-assignment/elem`,
        shs: `${ROOTS.DASHBOARD}/registrar/section-assignment/shs`,
      },
      sectionOffering: `${ROOTS.DASHBOARD}/registrar/section-offering`,
      setup: {
        root: `${ROOTS.DASHBOARD}/registrar/setup`,
        compreUnitsGs: `${ROOTS.DASHBOARD}/registrar/setup/compre-units-gs`,
        courseGradePrerequisite: `${ROOTS.DASHBOARD}/registrar/setup/course-grade-prerequisite`,
        curriculumCollege: `${ROOTS.DASHBOARD}/registrar/setup/curriculum-college`,
        curriculumGs: `${ROOTS.DASHBOARD}/registrar/setup/curriculum-gs`,
        curriculumShs: `${ROOTS.DASHBOARD}/registrar/setup/curriculum-shs`,
        curriculumElem: `${ROOTS.DASHBOARD}/registrar/setup/curriculum-elem`,
        curriculumTypeUnitsGs: `${ROOTS.DASHBOARD}/registrar/setup/curriculum-type-units-gs`,
        generalClearanceSignatories: `${ROOTS.DASHBOARD}/registrar/setup/general-clearance-signatories`,
        gradingSystem: {
          root: `${ROOTS.DASHBOARD}/registrar/setup/grading-system`,
          curriculum: `${ROOTS.DASHBOARD}/registrar/setup/grading-system/curriculum`,
          subject: `${ROOTS.DASHBOARD}/registrar/setup/grading-system/subject`,
        },
        gradeEquivalentCollege: `${ROOTS.DASHBOARD}/registrar/setup/grade-equivalent-college`,
        gradeEquivalentGs: `${ROOTS.DASHBOARD}/registrar/setup/grade-equivalent-gs`,
        sectionCollege: `${ROOTS.DASHBOARD}/registrar/setup/section-college`,
        sectionElem: `${ROOTS.DASHBOARD}/registrar/setup/section-elem`,
        subjectCollege: `${ROOTS.DASHBOARD}/registrar/setup/subject-college`,
        subjectElem: `${ROOTS.DASHBOARD}/registrar/setup/subject-elem`,
        systemConfig: `${ROOTS.DASHBOARD}/registrar/setup/system-config`,
        yearLeveling: `${ROOTS.DASHBOARD}/registrar/setup/year-leveling`,
      },
      slotMonitoring: {
        root: `${ROOTS.DASHBOARD}/registrar/slot-monitoring`,
        college: `${ROOTS.DASHBOARD}/registrar/slot-monitoring/college`,
        shs: `${ROOTS.DASHBOARD}/registrar/slot-monitoring/shs`,
        elem: `${ROOTS.DASHBOARD}/registrar/slot-monitoring/elem`,
      },
      subjectTagging: {
        root: `${ROOTS.DASHBOARD}/registrar/subject-tagging`,
        penalty: `${ROOTS.DASHBOARD}/registrar/subject-tagging/penalty`,
        remedial: `${ROOTS.DASHBOARD}/registrar/subject-tagging/remedial`,
      },
      yearLeveling: {
        root: `${ROOTS.DASHBOARD}/registrar/year-leveling`,
        individual: `${ROOTS.DASHBOARD}/registrar/year-leveling/individual`,
        compute: `${ROOTS.DASHBOARD}/registrar/year-leveling/compute`,
      },
    },
    guidance: {
      root: `${ROOTS.DASHBOARD}/guidance`,
      applicationElem: {
        root: `${ROOTS.DASHBOARD}/guidance/application_elem`,
        form: `${ROOTS.DASHBOARD}/guidance/application_elem/form`,
        shsTransition: `${ROOTS.DASHBOARD}/guidance/application_elem/shs_transition`,
        elemTransition: `${ROOTS.DASHBOARD}/guidance/application_elem/elem_transition`,
        documents: `${ROOTS.DASHBOARD}/guidance/application_elem/documents`,
        interview: `${ROOTS.DASHBOARD}/guidance/application_elem/interview`,
        process: `${ROOTS.DASHBOARD}/guidance/application_elem/process`,
      },
      applicationCollege: {
        root: `${ROOTS.DASHBOARD}/guidance/application_college`,
        form: `${ROOTS.DASHBOARD}/guidance/application_college/form`,
        collegeTransition: `${ROOTS.DASHBOARD}/guidance/application_college/college_transition`,
        doubleMajor: `${ROOTS.DASHBOARD}/guidance/application_college/double_major`,
        documents: `${ROOTS.DASHBOARD}/guidance/application_college/documents`,
        ept: `${ROOTS.DASHBOARD}/guidance/application_college/ept`,
        interview: `${ROOTS.DASHBOARD}/guidance/application_college/interview`,
        process: `${ROOTS.DASHBOARD}/guidance/application_college/process`,
      },
      applicationGs: {
        root: `${ROOTS.DASHBOARD}/guidance/application_gs`,
        form: `${ROOTS.DASHBOARD}/guidance/application_gs/form`,
        gsTransition: `${ROOTS.DASHBOARD}/guidance/application_gs/gs_transition`,
        doubleMajor: `${ROOTS.DASHBOARD}/guidance/application_gs/double_major`,
        documents: `${ROOTS.DASHBOARD}/guidance/application_gs/documents`,
        gmat: `${ROOTS.DASHBOARD}/guidance/application_gs/gmat`,
        interview: `${ROOTS.DASHBOARD}/guidance/application_gs/interview`,
        process: `${ROOTS.DASHBOARD}/guidance/application_gs/process`,
      },
      shiftingCollege: `${ROOTS.DASHBOARD}/guidance/shifting_college`,
      gradeDeficiency: `${ROOTS.DASHBOARD}/guidance/grade_deficiency`,
    },
    dean: {
      root: `${ROOTS.DASHBOARD}/dean`,
      curriculumCollege: `${ROOTS.DASHBOARD}/dean/curriculum_college`,
      sectionOfferingElem: `${ROOTS.DASHBOARD}/dean/section_offering_elem`,
      sectionOfferingShs: `${ROOTS.DASHBOARD}/dean/section_offering_shs`,
      sectionOfferingCollege: `${ROOTS.DASHBOARD}/dean/section_offering_college`,
      sectionOfferingGs: `${ROOTS.DASHBOARD}/dean/section_offering_gs`,
      facultyLoadingCollege: `${ROOTS.DASHBOARD}/dean/faculty_loading_college`,
      facultyLoadingGs: `${ROOTS.DASHBOARD}/dean/faculty_loading_gs`,
      facultyLoadingSchedule: `${ROOTS.DASHBOARD}/dean/faculty_loading_schedule`,
      maxUnitsAllowedGs: `${ROOTS.DASHBOARD}/dean/max_units_allowed_gs`,
      comprehensiveExamGs: `${ROOTS.DASHBOARD}/dean/comprehensive_exam_gs`,
      comprehensiveExamApprovalGs: `${ROOTS.DASHBOARD}/dean/comprehensive_exam_approval_gs`,
      comprehensiveExamGradeGs: `${ROOTS.DASHBOARD}/dean/comprehensive_exam_grade_gs`,
      roomAvailability: `${ROOTS.DASHBOARD}/dean/room_availability`,
      facultyAvailability: `${ROOTS.DASHBOARD}/dean/faculty_availability`,
      subjectsOffered: `${ROOTS.DASHBOARD}/dean/subjects_offered`,
      facultyScheduleQuery: `${ROOTS.DASHBOARD}/dean/faculty_schedule_query`,
      tutorialQuery: `${ROOTS.DASHBOARD}/dean/tutorial_query`,
      classScheduleQuery: `${ROOTS.DASHBOARD}/dean/class_schedule_query`,
      studentGradeDeficiency: `${ROOTS.DASHBOARD}/dean/student_grade_deficiency`,
      studentGradeRetention: `${ROOTS.DASHBOARD}/dean/student_grade_retention`,
      facultyEvaluationSchedule: `${ROOTS.DASHBOARD}/dean/faculty_evaluation_schedule`,
    },
    faculty: {
      root: `${ROOTS.DASHBOARD}/faculty`,
      gradingSheet: {
        kinder: `${ROOTS.DASHBOARD}/faculty/grading_sheet/kinder`,
        elemJhs: `${ROOTS.DASHBOARD}/faculty/grading_sheet/elem_jhs`,
        shs: `${ROOTS.DASHBOARD}/faculty/grading_sheet/shs`,
        college: `${ROOTS.DASHBOARD}/faculty/grading_sheet/college`,
        gs: `${ROOTS.DASHBOARD}/faculty/grading_sheet/gs`,
      },
    },
    student: {
      root: `${ROOTS.DASHBOARD}/student`,
      profile: `${ROOTS.DASHBOARD}/student/profile`,
      schedule: `${ROOTS.DASHBOARD}/student/schedule`,
      grades: `${ROOTS.DASHBOARD}/student/grades`,
      periodicalGrade: `${ROOTS.DASHBOARD}/student/periodical_grade`,
      ledger: `${ROOTS.DASHBOARD}/student/ledger`,
      enrollmentAssessment: `${ROOTS.DASHBOARD}/student/enrollment_assessment`,
      idMaster: `${ROOTS.DASHBOARD}/student/id_master`,
      changePassword: `${ROOTS.DASHBOARD}/student/change_password`,
    },
    reports: {
      root: `${ROOTS.DASHBOARD}/reports`,
      registrar: {
        root: `${ROOTS.DASHBOARD}/reports/registrar`,
        classSchedule: `${ROOTS.DASHBOARD}/reports/registrar/class-schedule`,
        facultyClassList: `${ROOTS.DASHBOARD}/reports/registrar/faculty-class-list`,
        enrollmentData: `${ROOTS.DASHBOARD}/reports/registrar/enrollment-data`,
        enrollmentDataYrLvlGender: `${ROOTS.DASHBOARD}/reports/registrar/enrollment-data-yr-lvl-gender`,
        enrollmentDataGender: `${ROOTS.DASHBOARD}/reports/registrar/enrollment-data-gender`,
        enrollmentList: `${ROOTS.DASHBOARD}/reports/registrar/enrollment-list`,
        enrollmentListBridgingCourse: `${ROOTS.DASHBOARD}/reports/registrar/enrollment-list-bridging-course`,
        subjectOffering: `${ROOTS.DASHBOARD}/reports/registrar/subject-offering`,
        yearLeveling: `${ROOTS.DASHBOARD}/reports/registrar/year-leveling`,
        enrolledStudents: `${ROOTS.DASHBOARD}/reports/registrar/enrolled-students`,
        certification: {
          root: `${ROOTS.DASHBOARD}/reports/registrar/certification`,
          certification: `${ROOTS.DASHBOARD}/reports/registrar/certification/certification`,
          certificationWithGwa: `${ROOTS.DASHBOARD}/reports/registrar/certification/certification-with-gwa`,
        },
        request: {
          root: `${ROOTS.DASHBOARD}/reports/registrar/request`,
          form137a: `${ROOTS.DASHBOARD}/reports/registrar/request/form-137-a`,
          sf10: `${ROOTS.DASHBOARD}/reports/registrar/request/sf10`,
        },
        studentGrades: `${ROOTS.DASHBOARD}/reports/registrar/student-grades`,
        applicationForGraduation: {
          root: `${ROOTS.DASHBOARD}/reports/registrar/application-for-graduation`,
          application: `${ROOTS.DASHBOARD}/reports/registrar/application-for-graduation/application`,
          manualTag: `${ROOTS.DASHBOARD}/reports/registrar/application-for-graduation/manual-tag`,
        },
        transcriptOfRecords: {
          root: `${ROOTS.DASHBOARD}/reports/registrar/transcript-of-records`,
          old: `${ROOTS.DASHBOARD}/reports/registrar/transcript-of-records/tor-old`,
          new: `${ROOTS.DASHBOARD}/reports/registrar/transcript-of-records/tor-new`,
          gs: `${ROOTS.DASHBOARD}/reports/registrar/transcript-of-records/tor-gs`,
        },
        gradingsheetReport: `${ROOTS.DASHBOARD}/reports/registrar/gradingsheet-report`,
        gwa: `${ROOTS.DASHBOARD}/reports/registrar/gwa`,
        gradeDeficiency: `${ROOTS.DASHBOARD}/reports/registrar/grade-deficiency`,
      },
      dean: {
        root: `${ROOTS.DASHBOARD}/reports/dean`,
        studentEvaluation: `${ROOTS.DASHBOARD}/reports/dean/student-evaluation`,
        summaryOfRatings: `${ROOTS.DASHBOARD}/reports/dean/summary-of-ratings`,
        classSchedule: `${ROOTS.DASHBOARD}/reports/dean/class-schedule`,
        facultySchedule: `${ROOTS.DASHBOARD}/reports/dean/faculty-schedule`,
        tutorialReport: `${ROOTS.DASHBOARD}/reports/dean/tutorial-report`,
        hrReport: `${ROOTS.DASHBOARD}/reports/dean/hr-report`,
        facultyByDepartment: `${ROOTS.DASHBOARD}/reports/dean/faculty-by-department`,
        room: {
          root: `${ROOTS.DASHBOARD}/reports/dean/room`,
          allRooms: `${ROOTS.DASHBOARD}/reports/dean/room/all-rooms-report`,
          byRoomSchedule: `${ROOTS.DASHBOARD}/reports/dean/room/by-room-schedule`,
          conflictSchedule: `${ROOTS.DASHBOARD}/reports/dean/room/conflict-schedule`,
        },
      },
      accounting: {
        root: `${ROOTS.DASHBOARD}/reports/accounting`,
        educationalIncomeSchedule: `${ROOTS.DASHBOARD}/reports/accounting/educational-income-schedule`,
        educationalIncomeSummary: `${ROOTS.DASHBOARD}/reports/accounting/educational-income-summary`,
        educationalIncomeTotalSummary: `${ROOTS.DASHBOARD}/reports/accounting/educational-income-total-summary`,
        studentsUnitsEnrolled: `${ROOTS.DASHBOARD}/reports/accounting/students-units-enrolled`,
        studentsTuitionFee: `${ROOTS.DASHBOARD}/reports/accounting/students-tuition-fee`,
        studentsTuitionUnits: `${ROOTS.DASHBOARD}/reports/accounting/students-tuition-units`,
        individualAssessment: `${ROOTS.DASHBOARD}/reports/accounting/individual-assessment`,
        statementOfAccount: `${ROOTS.DASHBOARD}/reports/accounting/statement-of-account`,
        tuitionMiscLab: `${ROOTS.DASHBOARD}/reports/accounting/tuition-misc-lab`,
        admissionSlip: {
          root: `${ROOTS.DASHBOARD}/reports/accounting/admission-slip`,
          slip: `${ROOTS.DASHBOARD}/reports/accounting/admission-slip/slip`,
          generate: `${ROOTS.DASHBOARD}/reports/accounting/admission-slip/generate`,
          ind: `${ROOTS.DASHBOARD}/reports/accounting/admission-slip/ind`,
        },
        accountSlip: `${ROOTS.DASHBOARD}/reports/accounting/account-slip`,
        receivables: `${ROOTS.DASHBOARD}/reports/accounting/receivables`,
        dailyCollection: `${ROOTS.DASHBOARD}/reports/accounting/daily-collection`,
        voidPayments: `${ROOTS.DASHBOARD}/reports/accounting/void-payments`,
        subjectFee: `${ROOTS.DASHBOARD}/reports/accounting/subject-fee`,
        debitCreditDiscount: {
          root: `${ROOTS.DASHBOARD}/reports/accounting/debit-credit-discount`,
          summary: `${ROOTS.DASHBOARD}/reports/accounting/debit-credit-discount/summary`,
          cashDiscount: `${ROOTS.DASHBOARD}/reports/accounting/debit-credit-discount/cash-discount`,
          creditDebit: `${ROOTS.DASHBOARD}/reports/accounting/debit-credit-discount/credit-debit`,
        },
        studentBalance: `${ROOTS.DASHBOARD}/reports/accounting/student-balance`,
      },
    },
    basicEducation: {
      root: `${ROOTS.DASHBOARD}/basic-education`,
      classSchedule: `${ROOTS.DASHBOARD}/basic-education/class-schedule`,
      hideGradesElem: `${ROOTS.DASHBOARD}/basic-education/hide-grades-elem`,
      hideGradesShs: `${ROOTS.DASHBOARD}/basic-education/hide-grades-shs`,
      shsTransferIrreg: `${ROOTS.DASHBOARD}/basic-education/shs-transfer-irreg`,
      studentProfileBe: `${ROOTS.DASHBOARD}/basic-education/student-profile-be`,
    },
    saao: {
      root: `${ROOTS.DASHBOARD}/saao`,
      goodMoral: `${ROOTS.DASHBOARD}/saao/goodmoral-cert`,
    },
    clearance: {
      root: `${ROOTS.DASHBOARD}/clearance`,
      viewCollege: `${ROOTS.DASHBOARD}/clearance/view-college`,
      tagging: {
        root: `${ROOTS.DASHBOARD}/clearance/tagging`,
        deansOffice: `${ROOTS.DASHBOARD}/clearance/tagging/deans-office`,
        studentAffairs: `${ROOTS.DASHBOARD}/clearance/tagging/student-affairs`,
        studentCouncil: `${ROOTS.DASHBOARD}/clearance/tagging/student-council`,
        library: `${ROOTS.DASHBOARD}/clearance/tagging/library`,
        guidanceOffice: `${ROOTS.DASHBOARD}/clearance/tagging/guidance-office`,
        school: {
          root: `${ROOTS.DASHBOARD}/clearance/tagging/school`,
          accountancy: `${ROOTS.DASHBOARD}/clearance/tagging/school/accountancy`,
          liberalArts: `${ROOTS.DASHBOARD}/clearance/tagging/school/liberal-arts`,
          business: `${ROOTS.DASHBOARD}/clearance/tagging/school/business`,
          hospitalityTourism: `${ROOTS.DASHBOARD}/clearance/tagging/school/hospitality-tourism`,
          criminalJustice: `${ROOTS.DASHBOARD}/clearance/tagging/school/criminal-justice`,
          education: `${ROOTS.DASHBOARD}/clearance/tagging/school/education`,
          it: `${ROOTS.DASHBOARD}/clearance/tagging/school/it`,
          engineering: `${ROOTS.DASHBOARD}/clearance/tagging/school/engineering`,
          architectureFineArts: `${ROOTS.DASHBOARD}/clearance/tagging/school/architecture-fine-arts`,
        },
      },
      aaoTaggingGraduates: `${ROOTS.DASHBOARD}/clearance/aao-tagging-graduates`,
    },
  },
};

